Training Batch: 1/47: 0it [00:00, ?it/s]                                                                               | 0/100 [00:00<?, ?it/s]
Epoch: 1/100:   0%|                                                                                                    | 0/100 [00:09<?, ?it/s]
Traceback (most recent call last):
  File "/Users/akchunya/Projects/WSD-without-compromise/tests/cards_latent_dim_text.py", line 202, in <module>
    train()
  File "/Users/akchunya/Projects/WSD-without-compromise/tests/cards_latent_dim_text.py", line 96, in train
    for i, data in tqdm(enumerate(train_dataloader), f"Training Batch: {train_loop_num}/{len(train_dataloader)}"):
  File "/Users/akchunya/miniforge3/envs/WSD-WO-COMp/lib/python3.11/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/Users/akchunya/miniforge3/envs/WSD-WO-COMp/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/Users/akchunya/miniforge3/envs/WSD-WO-COMp/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akchunya/miniforge3/envs/WSD-WO-COMp/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/Users/akchunya/miniforge3/envs/WSD-WO-COMp/lib/python3.11/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/Users/akchunya/miniforge3/envs/WSD-WO-COMp/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/akchunya/miniforge3/envs/WSD-WO-COMp/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akchunya/miniforge3/envs/WSD-WO-COMp/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 398, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akchunya/miniforge3/envs/WSD-WO-COMp/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 211, in collate
    return [
           ^
  File "/Users/akchunya/miniforge3/envs/WSD-WO-COMp/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 212, in <listcomp>
    collate(samples, collate_fn_map=collate_fn_map)
  File "/Users/akchunya/miniforge3/envs/WSD-WO-COMp/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 240, in collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'PIL.Image.Image'>
